### ISSUE TITLE
What is your favourite food?

### ISSUE THREAD

**Issue by jxom** [hugomd/ama#1]

**Comment by hugomd** [comment]
@jxom I think I like to many foods to just name one favourite, so I'll list a few:
* Green mango with sugar and chilli salt, [recipe](http://archive.urbanjunkies.com/08/0319-mango.html)
* Margherita pizza with a thin base, rich tomatoes and a few leaves of basil
* Rice pudding
* Pain au chocolat
* Fresh bread with olive oil and salt
* [Beef Bourguignon](https://en.wikipedia.org/wiki/Beef_bourguignon)
* Cheese fondu
* Raclette

**Comment by jxom** [comment]
That is a great list!
